spring.application.name: greenlight-prototype-admin-api
spring.profiles.active: local

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.winten.greenlight.prototype
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

server:
  port: 8090
  error:
    include-message: always

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    root: INFO
    com.winten: DEBUG

---
spring.config.activate.on-profile: local
spring:
  datasource:
    url: ${STORAGE_POSTGRESQL_URL}
    username: ${STORAGE_POSTGRESQL_USERNAME}
    password: ${STORAGE_POSTGRESQL_PASSWORD}
  data:
    redis:
      host: ${STORAGE_REDIS_HOST}
      port: ${STORAGE_REDIS_PORT}
      password: ${STORAGE_REDIS_PASSWORD}
---
spring.config.activate.on-profile: dev
spring:
  datasource:
    url: ${STORAGE_POSTGRESQL_URL}
    username: ${STORAGE_POSTGRESQL_USERNAME}
    password: ${STORAGE_POSTGRESQL_PASSWORD}
  data:
    redis:
      host: ${STORAGE_REDIS_HOST}
      port: ${STORAGE_REDIS_PORT}
      password: ${STORAGE_REDIS_PASSWORD}

---
spring.config.activate.on-profile: live
spring:
  datasource:
    url: ${STORAGE_POSTGRESQL_URL}
    username: ${STORAGE_POSTGRESQL_USERNAME}
    password: ${STORAGE_POSTGRESQL_PASSWORD}
  data:
    redis:
      host: ${STORAGE_REDIS_HOST}
      port: ${STORAGE_REDIS_PORT}
      password: ${STORAGE_REDIS_PASSWORD}