spring.application.name: greenlight-admin-api
spring.profiles.active: local

server:
  port: 28080
  error:
    include-message: always
  url: ${SERVER_URL}

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  data:
    redis:
      cluster:
        max-redirects: 3

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.winten.greenlight
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    root: INFO
    com.winten: DEBUG

influxdb:
  url: ${INFLUXDB_URL}
  token: ${INFLUXDB_TOKEN}
  org: ${INFLUXDB_ORG}
  bucket: ${INFLUXDB_BUCKET}

springdoc:
  swagger-ui:
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: -1
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

custom:
  redis:
    key-prefix: ${REDIS_KEY_PREFIX}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

greenlight:
  core-api:
    url: ${GREENLIGHT_CORE_API_URL}

---
spring.config.activate.on-profile: local
spring:
  datasource:
    url: ${STORAGE_POSTGRESQL_URL}
    username: ${STORAGE_POSTGRESQL_USERNAME}
    password: ${STORAGE_POSTGRESQL_PASSWORD}
  data:
    redis:
      cluster:
        nodes:
          - ${REDIS_CLUSTER_MASTER_NODE_1}
          - ${REDIS_CLUSTER_MASTER_NODE_2}
          - ${REDIS_CLUSTER_MASTER_NODE_3}
          - ${REDIS_CLUSTER_WORKER_NODE_1}
          - ${REDIS_CLUSTER_WORKER_NODE_2}
          - ${REDIS_CLUSTER_WORKER_NODE_3}
      password: ${REDIS_PASSWORD}
---
spring.config.activate.on-profile: dev
spring:
  datasource:
    url: ${STORAGE_POSTGRESQL_URL}
    username: ${STORAGE_POSTGRESQL_USERNAME}
    password: ${STORAGE_POSTGRESQL_PASSWORD}
  data:
    redis:
      cluster:
        nodes:
          - ${REDIS_CLUSTER_MASTER_NODE_1}
          - ${REDIS_CLUSTER_MASTER_NODE_2}
          - ${REDIS_CLUSTER_MASTER_NODE_3}
          - ${REDIS_CLUSTER_WORKER_NODE_1}
          - ${REDIS_CLUSTER_WORKER_NODE_2}
          - ${REDIS_CLUSTER_WORKER_NODE_3}
      password: ${REDIS_PASSWORD}
---
spring.config.activate.on-profile: live
spring:
  datasource:
    url: ${STORAGE_POSTGRESQL_URL}
    username: ${STORAGE_POSTGRESQL_USERNAME}
    password: ${STORAGE_POSTGRESQL_PASSWORD}
  data:
    redis:
      cluster:
        nodes:
          - ${REDIS_CLUSTER_MASTER_NODE_1}
          - ${REDIS_CLUSTER_MASTER_NODE_2}
          - ${REDIS_CLUSTER_MASTER_NODE_3}
          - ${REDIS_CLUSTER_WORKER_NODE_1}
          - ${REDIS_CLUSTER_WORKER_NODE_2}
          - ${REDIS_CLUSTER_WORKER_NODE_3}
      password: ${REDIS_PASSWORD}
logging:
  level:
    root: ERROR
    com.winten: ERROR
    com.winten.greenlight: ERROR